# Generated by Django 3.2.9 on 2021-12-10 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pokemon1', models.CharField(max_length=20)),
                ('pokemon2', models.CharField(max_length=20)),
                ('pokemon3', models.CharField(max_length=20)),
                ('pokemon4', models.CharField(max_length=20)),
                ('pokemon5', models.CharField(max_length=20)),
            ],
        ),
    ]
