# Generated by Django 3.2.9 on 2021-12-10 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamPokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pokemon1', models.CharField(max_length=20)),
                ('pokemon2', models.CharField(max_length=20)),
                ('pokemon3', models.CharField(max_length=20)),
                ('pokemon4', models.CharField(max_length=20)),
                ('pokemon5', models.CharField(max_length=20)),
            ],
        ),
    ]
